# config.py
import math

# --- SIEC ---
BROKER_ADDRESS = "192.168.1.1"
BROKER_PORT = 1883

TOPIC_SET_VELOCITY = "odrive/set_velocity"
TOPIC_FEEDBACK     = "odrive/feedback"
TOPIC_CMD          = "odrive/cmd"

# --- STEROWANIE ---
ABSOLUTE_MAX_LIMIT = 30.0  
JOYSTICK_DEADZONE = 0.2     
STEERING_AXIS_INDEX = 4    # Oś 5

# --- FIZYKA KOŁA ---
WHEEL_DIAMETER_CM = 45.0
GEAR_RATIO = 100.8
WHEEL_CIRCUMFERENCE_M = (WHEEL_DIAMETER_CM / 100.0) * math.pi
DISTANCE_PER_MOTOR_REV = WHEEL_CIRCUMFERENCE_M / GEAR_RATIO

# --- GUI COLORS ---
BG_COLOR = "#1e1e1e"
FG_COLOR = "#ffffff"
BTN_RESET_COLOR = "#cc3333"
BTN_CMD_COLOR = "#0055aa"
BTN_FULL_START_COLOR = "#228822"
BTN_REBOOT_COLOR = "#aa0000"
BTN_DUMP_COLOR = "#d35400"